name: "Катя рисует"
picture: "assets/img/picture.jpg"
bio: "рисую и придумываю для детей 🐞 🧚🏻‍♀️ 🐛 🧸"
meta:
  lang: "ru"
  description: "рисую и придумываю для детей 🐞 🧚🏻‍♀️ 🐛 🧸"
  title: "Катя рисует 🖌️"
  author: "Катя"
  siteUrl: ""
links:
  - name: "Pinterest"
    url: "https://pin.it/2odb0mdwU"
  - name: "Telegram"
    url: "https://t.me/katya_risyet"
  # - name: ""
  #   url: ""
theme: "custom"
